# Generated by Django 5.2.4 on 2025-08-26 11:09

import map.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=map.models.point_image_upload_to)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
