/**
 * Константы режимов пользовательского интерфейса
 */
export const UI_MODE = {
    MAIN_LIST: 'MAIN_LIST',
    CREATE_ROUTE: 'CREATE_ROUTE',
    EDIT_ROUTE: 'EDIT_ROUTE',
    CREATE_POINT: 'CREATE_POINT',
    EDIT_POINT: 'EDIT_POINT',
    VIEW_ROUTE_DETAILS: 'VIEW_ROUTE_DETAILS'
};

/**
 * Типы действий для редьюсера
 */
export const ACTION_TYPES = {
    // Загрузка и ошибки
    SET_LOADING: 'SET_LOADING',
    SET_ERROR: 'SET_ERROR',

    // Маршруты
    FETCH_ROUTES_SUCCESS: 'FETCH_ROUTES_SUCCESS',
    SET_CURRENT_ROUTE: 'SET_CURRENT_ROUTE',
    CLEAR_CURRENT_ROUTE: 'CLEAR_CURRENT_ROUTE',
    UPDATE_CURRENT_ROUTE_POINTS: 'UPDATE_CURRENT_ROUTE_POINTS',

    // Превью маршрута
    SET_PREVIEW_ROUTE: 'SET_PREVIEW_ROUTE',
    CLEAR_PREVIEW_ROUTE: 'CLEAR_PREVIEW_ROUTE',

    // Точки
    SET_POINT_TO_EDIT: 'SET_POINT_TO_EDIT',
    CLEAR_POINT_TO_EDIT: 'CLEAR_POINT_TO_EDIT',
    SET_TEMP_POINT_COORDS: 'SET_TEMP_POINT_COORDS',

    // UI режимы
    SET_UI_MODE: 'SET_UI_MODE',
    SET_WAITING_FOR_COORDINATES: 'SET_WAITING_FOR_COORDINATES',
    SET_QUICK_CREATE_MODE: 'SET_QUICK_CREATE_MODE',
};
